[workspace]
resolver = "3"
members = ["ferogram", "ferogram-macros"]

[workspace.package]
version = "0.2.0"
authors = ["Andriel Ferreira <andrielfr@proton.me>"]
edition = "2024"
readme = "README.md"
homepage = "https://github.com/AmanoTeam/ferogram"
repository = "https://github.com/AmanoTeam/ferogram"
license = "MIT"
keywords = ["bot", "framework", "grammers", "telegram"]

[workspace.dependencies]
grammers = {
  package = "grammers-client",
  git = "https://codeberg.org/Lonami/grammers",
  rev = "8170b6"
}
grammers-session = {
  git = "https://codeberg.org/Lonami/grammers",
  rev = "8170b6"
}

libsql = "0.9"
thiserror = "2.0"
tracing = "0.1"

# Futures
async-recursion = "1.1"
futures-core = {
  version = "0.3",
  default-features = false,
  features = ["alloc"]
}
tokio = {
  version = "1",
  default-features = false,
  features = ["rt-multi-thread", "signal", "sync"]
}

[patch.crates-io]
ferogram = { path = "ferogram" }
