[package]
name = "ferogram"
description = "A set of friendly libraries to make your deal with Telegram API through grammers easier."

version.workspace = true
authors.workspace = true
edition.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[lib]
doctest = false

[[example]]
name = "from-env"
path = "examples/from-env.rs"

[[example]]
name = "dispatcher"
path = "examples/dispatcher.rs"

[[example]]
name = "dispatcher-with-macros"
path = "examples/dispatcher-with-macros.rs"
required-features = ["macros"]

[dependencies]
ferogram-macros = { path = "../ferogram-macros", optional = true }

# Telegram
grammers.workspace = true
grammers-session.workspace = true

dashmap = "6.2"
inventory = { version = "0.3", optional = true }
regex = "1.13"
rpassword = "7.5"
url = { version = "2.5", optional = true }

libsql.workspace = true
thiserror.workspace = true
tracing.workspace = true

# Futures
async-recursion.workspace = true
futures-core.workspace = true
tokio.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros"] }

[features]
default = ["url"]

macros = ["dep:ferogram-macros", "dep:inventory"]
url = ["dep:url"]
